### ISSUE TITLE
Number of frames in a row

### ISSUE THREAD

**Issue by taylorjhunt** [kawamurakazushi/figma-format#1]
Currently it seems like the number of frames in a row is limited to 11, and any additional frames in the group break to a new row. Would be great if it was possible to have an unlimited number of frames in a row without ever breaking.

**Comment by kawamurakazushi** [comment]
@taylorjhunt Thanks for opening an issue!
I just published a new release to add options to customize the wrap count.
By putting a large number, i thought it would fit your needs.

Please let me now if you have any other feedbacks!

**Comment by kawamurakazushi** [comment]
I'll close this issue, Feel free to reopen if there is any problem.
