### ISSUE TITLE
I can't organize artboards what include numbers at beginning

### ISSUE THREAD

**Issue by josealvarezn** [kawamurakazushi/figma-format#2]
<img width="240" alt="image" src="https://user-images.githubusercontent.com/16816916/70841724-12546280-1df3-11ea-8d3e-ab9e28ffa3d3.png">

I want to organize my screens artboards, but my team and I have specific formatting for screens names. For example:

01.00_Screen name
- 01.01_Screen name (child)
- 01.02_Screen name (child)

02.00_Screen name
- 02.01_Screen name (child)
- 02.02_Screen name (child)

We pretend to combine with the / separator to organize them. Cand you help me, please?
Thanks!

**Comment by kawamurakazushi** [comment]
@josealvarezn 
Thanks for opening an issue!

If I understand correctly, I think it will solve by setting the  `Group Seperator` to `.`, in your configuration.

<img width="410" alt="Wireframe" src="https://user-images.githubusercontent.com/7858158/70847423-8f411400-1ea7-11ea-8cfa-160f4f2779b8.png">

**Comment by josealvarezn** [comment]
You're right, thank you very much! Works perfectly!

**Comment by kawamurakazushi** [comment]
NIce! thanks!
