### ISSUE TITLE
Select specific separator instance, not just the first match

### ISSUE THREAD

**Issue by nohuex** [kawamurakazushi/figma-format#3]
Hello, thank you for providing such a great plugin. It is the closest thing I've found to Symbol Organizer for Sketch. One limitation I've found is that typically we use "/" to organise our libraries into multiple levels, so the dropdowns are optimised when trying to select a component from the design files. But when trying to organise the library, we don't necessarily want the plugin to use the very first "/" it encounters in the name as the trigger for the split. Any way around it so we can specify whether to use the first, second, third "/" match etc?

Example component names:
`Navigation / Logged in / Component 1`
`Navigation / Logged in / Component 2`
`Navigation / Logged out / Component 1`
`Navigation / Logged out / Component 2`

We might want to group together everything that is part of the "Logged in" group, but if we use "/" in the plugin, they all get grouped together because of the "Navigation" parent group.

Thank you

**Comment by dylandeheer** [comment]
@nohuex → cant you solve this by using `Navigation / Logged in / ` as the divider?

**Comment by nohuex** [comment]
> @nohuex → cant you solve this by using `Navigation / Logged in / ` as the divider?

Thank you for the suggestion. Yes, I suppose I could use it but that would mean I would have to apply the Format only to those components under the Navigation category. It wouldn't work to rearrange the full library with one click, given Navigation is only one of many many categories.

**Comment by kawamurakazushi** [comment]
@nohuex thanks for the issue! 
It's currently work in progress!
