### ISSUE TITLE
Components with capitals do not sort correctly

### ISSUE THREAD

**Issue by rdimascio** [kawamurakazushi/figma-format#6]
![2020-07-07 13 40 04](https://user-images.githubusercontent.com/17639082/86841777-390d0b80-c059-11ea-9a5f-311e9dd055df.gif)

### Expected Behavior:

The expected behavior is to sort A-Z: Adobe, AWS, Chrome, CSS, Webpack, WebStorm.

### Actual Behavior:

Frames with capital letters in any part of the string get sorted ahead of frames with lowercase: AWS, Adobe, CSS, Chrome, WebStorm, Webpack.

**Comment by kawamurakazushi** [comment]
@rdimascio It's published, please take a look and try :D
